### ISSUE TITLE
Add linter to evade number of issues

### ISSUE THREAD

**Issue by agrrh** [nett00n/traefik-certs-exporter#4]
There's number of issues in current code state:

Comment expected here as this struct is exported:
https://github.com/nett00n/traefik-certs-exporter/blob/6c0383df48baedff05f688b71ca4c62df8b09bb9/traefik-certs-exporter.go#L11

Underscores not encouraged in var names, better use `certBody`:
https://github.com/nett00n/traefik-certs-exporter/blob/6c0383df48baedff05f688b71ca4c62df8b09bb9/traefik-certs-exporter.go#L56

... and so on.

I'd propose to use one of:

- https://revive.run/
- https://golangci-lint.run/

**Comment by nett00n** [comment]
Fixed
